export const doctorList = [
  {
    id: 1,
    name: 'John Doe',
    employeeNumber: 792374898724,
    department: 'Sales',
    contact: 'john.doe@example.com',
    position: 'Sales Manager',
    reservationStatus: 'Confirmed',
    availableDate: '2022-01-01',
    cancelDate: null,
    medicalCondition: 'None',
    registerDate: '2022-01-01',
  },
  {
    id: 2,
    name: 'Jane Smith',
    employeeNumber: 5646547456,
    department: 'Marketing',
    contact: 'jane.smith@example.com',
    position: 'Marketing Manager',
    reservationStatus: 'Pending',
    availableDate: '2022-02-01',
    cancelDate: null,
    medicalCondition: 'None',
    registerDate: '2022-02-01',
  },
  {
    id: 3,
    name: 'Bob Johnson',
    employeeNumber: 6546546546,
    department: 'IT',
    contact: 'bob.johnson@example.com',
    position: 'IT Manager',
    reservationStatus: 'Cancelled',
    availableDate: '2022-03-01',
    cancelDate: '2022-03-15',
    medicalCondition: 'None',
    registerDate: '2022-03-01',
  },
];
